FROM golang:1.18-alpine3.15 AS build-stage

WORKDIR /usr/src/app

COPY . .
RUN go build -v -o ./bin/server


FROM alpine:3.15.4

EXPOSE 3000
WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/bin/server /usr/src/app/
COPY ./data ./data

RUN adduser -D appuser
USER appuser

CMD ["./server"]
