version: "3.9"
services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - .env.postgres
  api:
    build: ..
    ports:
      - 8080:8080
    environment:
      FAKE_DATABASE_URL: postgresql://user:password@postgres:5432/fake?sslmode=disable
    depends_on:
      - postgres
