name: Deploy container to Heroku

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: warm-everglades-72556
      url: https://warm-everglades-72556.herokuapp.com
    steps:
      - uses: actions/checkout@v2
      - uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_name: Dockerfile.public
          docker_options: "--no-cache"
